name: PR Validation

on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      
      - name: Clean Project
        run: dotnet clean
          
      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Build Project
        run: dotnet build --configuration Release --no-restore
        
      - name: Run Unit Tests
        run: dotnet test src/World.Net.UnitTests --configuration Release --no-build --verbosity normal

     # - name: Run Code Formatter
     #   run: dotnet format --check
